version: '2'
services:
  db:
    image: postgres
  web:
    environment:
      DJANGO_PORT: 8001
    build: .
    command: ./run.sh
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db